spam_words = [
    "free", 
    "offer", 
    "winner", 
    "win", 
    "prize", 
    "claim", 
    "congratulations",
    "urgent", 
    "immediate", 
    "action", 
    "limited time",
    "cash", 
    "bonus", 
    "earn", 
    "income", 
    "credit", 
    "loan",
    "call now", 
    "subscribe", 
    "click", 
    "apply",  
    "exclusive", 
    "mystery", 
    "gift", 
    "voucher", 
    "insurance", 
    "guaranteed",
    "enlargement",
    "guaranteed",
    "urgent",
    "private",
    "dating",
    "anti-aging",
    "anti aging",
    "no win",
    "no fee",
    "injury",
    "not your fault",
    "no-cost",
    "no cost",
    "vulnerabilities",
    "hacked",
    "hack",
    "single",
    "jackpot", 
    "millionaire", 
    "rich", 
    "discount", 
    "save",
    "profits",
    "weight loss", 
    "pharmacy", 
    "medication", 
    "supplement", 
    "enhancement", 
    "beauty",
    "exclusive deal", 
    "secret", 
    "elite", 
    "premium", 
    "luxury", 
    "best price",
    "hurry", 
    "immediately", 
    "one-time offer", 
    "last chance", 
    "before it's gone",
    "miracle", 
    "magic", 
    "risk-free", 
    "no credit check", 
    "no fees",
    "guarantee", 
    "promise", 
    "risk-free", 
    "no obligation", 
    "no risk",
    "transfer", 
    "payment", 
    "invoice", 
    "deal", 
    "bargain",
    "lawsuit", 
    "notice", 
    "warning", 
    "alert", 
    "verification",
    "password", 
    "account", 
    "security", 
    "update", 
    "confirm",
    "shocking", 
    "incredible", 
    "amazing", 
    "unbelievable", 
    "fantastic",
    "won",
    "call",
    "sexy",
    "vouchers",
    "text",
    "naked",
    "women",
    "babes",
    "shag",
    "entry",
    "unsubscribe",
    "competition"
]

print(list(set(spam_words)))